- README.md
Hi,
I think you've mixed up row/columns there - the x-axis, or horizontal line, would specify the column, not the row (and similarly for the y-axis).
Cheers :)
> Fix typo and row/col mix-up

- color.h
- global.cpp
- global.h
The discussion on issue #9 had a different solution, but I thought this way fit better than a macro.
The bug (re: 1's) was observed on macOS, where the output stream got "true" (therefore: 1's)
Thanks for writing this project. P.S. Love the vim keys, but would be nice if arrows worked.
> Fixes issue #9, re: use of bold_on, bold_off

- game.cpp
Keypress values were magic numbers. Namedspaced enum-named values
makes source code easier to understand.
> Fix: game-input: Keypress values converted into enums

- menu.cpp
Removed unneeded return statement from void function.  
_(This was previously omitted from last PR. This is a new PR because less risk of messing up git repository)_
> Fix: showScores: return statement from void

- game.cpp
- game.hpp
Made a new separate ui component for displaying the score(box). 
Spacing of text elements and border padding made less brittle and less dependent on global `std::cout`, `std::setw` and `std::endl` functions.
> Fix: drawBoard: Decouple some ui elements into individual components

- src/headers/color.hpp
Highly recommended http://www.stroustrup.com/C++11FAQ.html#enum
> Make Color to be scoped enumeration

- src/game.cpp
- src/headers/game.hpp
- src/headers/point2d.hpp
[As title description]
This PR was hinted to arrive from [PR:69](https://github.com/plibither8/2048.cpp/pull/69/commits/0c2e4a02a7d13684546c6cfc471b0b701360687f#diff-18513665750ef5adf42b5ec29e14162eR134).
This greatly helps developers understand context for parameters in interfaces around the codebase.
> Fix: Wrap parameters and variables around new datatype: point2D_t

- src/game.cpp
Highlights:
- Removed the `Please enter any key to exit.` user input to exit the game - it was unnecessary and started to bug. In place of that, we can ask the player whether they want to return to the menu.
- minor grammatical fixes to some sentences.
> Fix: Minor grammar fixes, remove game-exit input prompt

- src/game.cpp
- src/gameboard.cpp
- src/menu.cpp
- src/scores.cpp
[This PR is intended to be squashed into one major commit.] :card_file_box: 
[The PR is unsquashed for now as individual commits help in reviewing changes and understanding the changes' history / timeline.] :mag: :watch: 
This PR refactors a lot of hard (magic) values and use of the global `std::cout` function for many string formatting tasks.
It is replaced with `std::ostringstream`.
This is to help with setting up testing in the near future.
This PR code-style (i.e. declaration of fixed values defined at the beginning of the function) is needed for when testing is added for each individual function in the future.
_N.B. `std::cin` usage has not been refactored in this PR. It will be done in a future PR._
> Fix: reduce std::cout usage

- src/game.cpp
- src/gameboard.cpp
- src/headers/game.hpp
- src/headers/gameboard.hpp
[This commit will be squashed] :card_file_box: 
* Moves some independent code inside of GameBoard{} into their own function and into the anonymous namespace area.
* Removes unneeded functions and makes printing-to-cout functions a bit clearer to understand.
> Fix: Cleanup & Refactor GameBoard{}

- src/game.cpp
- src/headers/game.hpp
- src/headers/gameboard.hpp
[This commit can be squashed into one commit if needed] :card_file_box: 
This PR:
* fixes loading saved game data. 
It also makes the loading of data a bit more robust.
* partially makes code to load a `GameBoard{}` more generic.
> Fix: Loading Saved Game Data

- src/game.cpp
- src/headers/game.hpp
* _"Input"_ (Keypress) logic and _"Game Action"_ logic have been separated quite a bit.
This helps breaks up the main _input_ function into smaller ones based on a _"keypress"_ style.
* _Keypress styles_ now have their own functions.
* This makes it easier to test if keypresses are working.
* Keypresses now _"flag an intent"_ for the game _"to do X action"_.
* _"Flag"_-based processing introduced in the game.
In this PR...
* `GameStatusFlag` for all game-related statuses like _win_ / _lose_ / _save_ (and returning soon _endless-mode_)...
* `IntendedMoveFlag` for all move-related statuses like "tumbleLeft" or "tumbleRight".
* This will help in creating _"replayable"-based tests_.
* Will be encapsulated / separated further in a future PR.
* Depending on which flags enabled / disabled, …
> Fix: Refactored Inputs and some UI from Game Logic

- src/headers/gameboard.hpp
I'm using GCC 8.2.1 and I got [-Wreorder] warning during compilation.
/home/tomasz/code/2048.cpp/src/headers/gameboard.hpp: In constructor ‘GameBoard::GameBoard(ull)’:                                                                         
/home/tomasz/code/2048.cpp/src/headers/gameboard.hpp:28:17: warning: ‘GameBoard::playsize’ will be initialized after [-Wreorder]                                          
ull playsize{0};                                                                                                                                                       
^                                                                                                                                                        
/home/tomasz/code/2048.cpp/src/headers/gameboard.hpp:27:21: …
> Fix compilation warning

- src/2048.cpp
- src/game.cpp
- src/global.cpp
- src/headers/global.hpp
- src/headers/menu.hpp
- src/menu.cpp
This PR cleans up the API to call the _"Main Menu"_ for _2048.cpp_.
One only just needs to add `menu.hpp` and to call `Menu::startMenu()`.
For example:
```cpp
#include "menu.hpp"
int main() {
Menu::startMenu();
}
```
Functions needed for the _2048.cpp's Main Menu_ are contained within _(menu.cpp's)_ own anonymous namespace.
> Fix: Convert Menu class to a namespaced area

- src/game.cpp
- src/global.cpp
- src/headers/global.hpp
- src/headers/scores.hpp
- src/headers/statistics.hpp
- src/menu.cpp
- src/scores.cpp
- src/statistics.cpp
This PR does a few things:
* _Converts_ `Stats` class into a _simple struct datastructure_.
* _Renames_ `Stats` datatype to a more appropriate name: `total_game_stats_t`.
* _Adds the standard conventions_ of using "`operator`" functions to write `total_game_stats_t` data to some sort of "`std::{??}stream`".
* _Namespaces datatype and its helper functions_ to avoid name conflicts and to prepare for a future loading / saving PR.
* Made a _"Pretty Print"_ function to display datatype in a table-like form.
> Fix: Convert Stats class to a namespaced area

- CMakeLists.txt
- meson.build
- src/game-graphics.cpp
- src/game-input.cpp
- src/game.cpp
- src/global.cpp
- src/headers/game-graphics.hpp
- src/headers/game-input.hpp
- src/headers/game.hpp
- src/headers/global.hpp
- src/headers/loadresource.hpp
- src/headers/saveresource.hpp
- src/headers/statistics.hpp
- src/loadresource.cpp
- src/menu.cpp
- src/saveresource.cpp
- src/statistics.cpp
- src/tile.cpp
Continued from PR #101 ...
_This is a large size PR and 98%~ complete so pushing changes._ :smiley: 
* Removes `Game` _class_ for a _namespace_.
* Added relevant `game-*` translation units _to help break up_ the large `game` translation unit.
* Removed a lot of _member variables_ of the previous `Game` _class_ into more local _function variables_.
* Moved _out-of-place functions_ (like `tileColor`) to better suited translation units.
* Introduced `loadresource` and `saveresource` _translation units_.
* A lot of _functions are now much more "stand-alone" and testable_!
* _Function names (and their parameters required)_ are much _more clearer and understandable_.
* _Repeated code / functionality_ has been _templated_. (See `Draw{Always,AsOneTimeFlag,OnlyWhen}`)
--
_Note: It may help to go …
> Fix: Convert Game class to a namespaced area

- src/global.cpp
- src/headers/global.hpp
- src/menu.cpp
- src/statistics.cpp
When user enters the highscore screen, a button press now returns the
user to the main-menu screen instead of quitting the program.
One can quit via the main-menu screen instead.
> Fix: Issue #67

- src/game-pregamemenu.cpp
- src/game.cpp
- src/gameboard.cpp
- src/headers/gameboard.hpp
- src/headers/tile.hpp
- src/saveresource.cpp
- src/tile.cpp
Continuing the trend from PR #102...
_This is a large PR so pushing the changes as it is mostly complete._
* Makes the `Gameboard` class into a _simple `struct` datatype_. (Check out the `gameboard.hpp` header file!)
* Converts (nearly all) member functions of `Gameboard` class into _free-standing functions_.
* Many free-standing functions now in _anonymous namespace_.
* `Gameboard` struct is in `Game` namespace.
* Renamed function names to be more understandable.
* Added more _"strong" datatypes_ to function parameters.
* Function parameters' required datatypes are now more _"local"_ to its translation unit declarations.
* Moved some out-of-place functions to other more appropriate translation units.
> Fix: Convert Gameboard class to a namespaced area

- src/game.cpp
- src/gameboard.cpp
- src/headers/gameboard.hpp
- src/headers/tile.hpp
- src/loadresource.cpp
- src/tile.cpp
* _Removes_ some unneeded member functions.
* Wraps some functions into the _anonymous namespace_ of translation unit.
* Cleans up some `#include` definitions.
> Fix: Convert Tile class to a simple struct datatype

- src/headers/game.hpp
- src/headers/gameboard.hpp
- src/headers/loadresource.hpp
- src/headers/saveresource.hpp
Adding certain #includes in header files can pull dependencies not needed in certain translation units.
By forward declaring the classes needed (in the header files), translation units can further #include what is required to complete a class definition, keeping definitions more local to their TU's scope.
> Fix: Forward declare GameBoard class in certain header files

- src/game-graphics.cpp
- src/game.cpp
- src/headers/game-graphics.hpp
- src/headers/saveresource.hpp
- src/headers/scores-graphics.hpp
- src/headers/scores.hpp
- src/headers/statistics-graphics.hpp
- src/headers/statistics.hpp
- src/saveresource.cpp
- src/scores-graphics.cpp
- src/scores.cpp
- src/statistics-graphics.cpp
- src/statistics.cpp
Summary:
* Removed `bestScore` from global TU namespace.
* Removed `gamePlayBoard` from global TU namespace.
* Removed "in-out" parameter variables from functions.
* Moved some functions from Game TU to more appropriate TUs.
* Added more descriptive custom-named definitions for helper tuple datatypes.
* Reduced even more dependency on `std::c{in, out}`.
* "Graphical output" functions are refactored to minimise "functional side-effects" (i.e. now only outputs one `std::string` datatype result; accepts only one "in"-type parameter).
> Fix: Refactored various items in Game TU

- src/headers/scores-graphics.hpp
- src/scores-graphics.cpp
* Travis build: 266.2 failed because of missing includes for std::{array, tuple}.
> Fix: Travis: Build 266.2: Missing includes for Scores-Graphics TU

- .replit
- README.md
Really cool implementation! 
I think it would be awesome if users could try the game (and even improve and commit to it) from the browser. Would you consider adding a "run on repl.it" badge? 
Here is how it will look like!
You can try it here: https://repl.it/@amasad/2048-cpp
> Docs: Add "run on repl.it" badge
