game.cpp

Adds [requested](https://www.reddit.com/r/cpp/comments/99y9jv/github_featured_my_tui_game_2048cpp_on_their/e4rij7x) vim binding support

add vim bindings support

---

2048.cpp
game.cpp
game.h

the <random> functions are much better at generating random numbers than the cstdlib rand() and srand() functions

changed cstdlib rand to c++ random int generator

---

CMakeLists.txt

to allow working on non-unix systems and enable IDE support

Provide a CMakeLists.txt

---

Makefile
game.cpp

Here is a patch to support ANSI arrow keys for play.

Arrow keys

---

game.cpp
game.h
scores.cpp
statistics.cpp
statistics.h

Check for stats and scores files before showing

---

game.cpp

Removed unneeded return statement from void function.

Fix: saveScore: return statement from void

---

CMakeLists.txt

Makes project file easier to read / edit (sections).

Fix: cmakelist: Separated properties to distinct sections

---

game.cpp

Add arrow keys on how to play instructions

---

src/game.cpp
src/headers/game.hpp

Removes a lot of magic numbers and fixes styling for some names as class member variables.
This will make the project easier to read for newcomers.

Fix: Readability: Magic numbers and class member variables

---

src/game.cpp
src/headers/game.hpp

Part of a bigger "Single responsibility principle" (SRP) refactor effort.
1: https://en.wikipedia.org/wiki/Single_responsibility_principle

Fix: Game::board: Encapsulate datamember into its own class

---

src/menu.cpp

Allow user choose to exit nicely instead of hitting `Ctrl+C`.

Add exit menu option

---

.appveyor.yml
.travis.yml
src/game.cpp
src/global.cpp
src/headers/game.hpp
src/headers/global.hpp
src/menu.cpp
src/scores.cpp

Fix: replace std::endl with newline character

---

README.md
src/game.cpp
src/headers/game.hpp

[As title description]
I have squashed the commits but kept some of the history's timeline. This is to help new learners understand how to refactor codebases.
Will merge swiftly if there are no objections (to prevent merge conflicts from new PRs).

Fix: GameBoard encapsulated; now uses an {x,y} coordinate system.

---

src/game.cpp
src/gameboard.cpp
src/headers/game.hpp
src/headers/gameboard.hpp

Highlights include:
* moving functions from Game{} to GameBoard{}
* moving some header code into its .cpp file
* Rewriting variables to be more descriptive
* Making functions to break up longer pieces of code blocks
* Deleting unneeded variables

Fix: Code Restructuring: GameBoard{} and Game{}

---

src/2048.cpp
src/game.cpp
src/gameboard.cpp
src/global.cpp
src/headers/2048.hpp
src/headers/game.hpp
src/headers/gameboard.hpp
src/headers/global.hpp
src/headers/menu.hpp
src/headers/scores.hpp
src/headers/statistics.hpp
src/headers/tile.hpp
src/menu.cpp
src/scores.cpp
src/statistics.cpp

* Moved a lot of `#includes` to source (`.cpp`) files.
* Removed double declarations of `#includes`

Cleanup: Dependencies in header and source files

---

README.md

hi, I clone this awesome job the follow your guide but i find it in step 4 cmake ../src dosen't work ,maybe you have moved the cmakelist.txt from src

fix readme step-4 'cmake ../src'

---

README.md

Similar to #92, this PR fixes the Meson build instructions.
Also, brushes up and formats some portions of the readme for better readability.

fix: Brush up Readme content, fix Meson build instruction

---

README.md

As a target of the project is to teach programming, the users may not yet realize how to switch to other free/paid compilers.
Also corrected spelling.

Add notes for manually selecting C++ compiler

---

.appveyor.yml
.travis.yml
CMakeLists.txt
meson.build
src/global.cpp
src/scores-graphics.cpp
src/statistics-graphics.cpp

* use builtin warning_level for Meson
* add test to CMake
* cleanup CI to use Ctest
* use default capture to allow MSVC to build.

allow build with Intel & MSVC compilers.

---

src/statistics-graphics.cpp

cleanup: clang-format

---

CMakeLists.txt
setup.cmake

Add the basic test for Windows as for Unix.

add windows test
